### ISSUE TITLE
sectorVault xChain balances

### ISSUE THREAD

**Issue by 0x0scion** [scion-finance/sector-contracts#38]
storing xVault share balances in SectorVault is error prone right now 
we should issue shares to SectorVault and add a mapping to store & manage xVault balances on SectorVault

**Comment by gcontarini** [comment]
this is being way harder than what I initially thought

**Comment by gcontarini** [comment]
making SectorVault the owner of xVault shares breaks all internal redeem as the withdraw ones

**Comment by 0x0scion** [comment]
instead lets generate an unique address for the vault:
pseudo code:
`address(uint160(uint(keccak256(abi.encodePacked(chianId, vaultAddrs)))))`)

it may not be gas efficient to do hashing every time, so we could cache these in a mapping...

**Comment by gcontarini** [comment]
done on branch `feat/sector-vault-xchain-test-and-final-adjustments`
