### ISSUE TITLE
Add fee validation logic to deposit/withdraw xChain calls

### ISSUE THREAD

**Issue by gcontarini** [scion-finance/sector-contracts#44]
To avoid MANAGER attacks, we are going to validate if the fees on a request is falling inside an expected "fixed" range. If the fees are higher than the setting the tx will revert. The GUARDIAN will be able to change this setting afterwards. An event should be emitted every time this settings is changed.

**Comment by 0x0scion** [comment]
There is still a danger the the receiving vault will get slightly less than the fee estimate.
For example, while doing e2e test, I ended up bridging 9664118, but the message had the value of 9664119, so the `processIncomingXFunds` was failing.

A crude workaround is to just send some underlying funds to the SectorVault in cases like this, but it would be to allow something like .1% slippage on the recipient side...

I guess we can also estimate-down the expected output when briding...

**Comment by gcontarini** [comment]
Implemented max checkFee logic on the sender. As discussed the manager will estimate up the bridge fees and saves us the trouble of checking it on the receiver side.
