### ISSUE TITLE
refactor depositQueue and withdrawQueue

### ISSUE THREAD

**Issue by 0x0scion** [scion-finance/sector-contracts#48]
depositQueue on SectorXVault and withdrawQueue on SectorVault are the same thing
- [x] we should move this method to XChainIntegrator and rename it to `incomingQueue`
- [x] make it public
- [x] add method to query length
- [x] add method to query whole array

**Comment by gcontarini** [comment]
done on branch `feat/sector-vault-xchain-test-and-final-adjustments` -> created incomingQueue as public in XChainIntegrator and getIncomingQueue to return array of messages and getIncomingQueueLength to return array size.
